# Generated by Django 2.2.5 on 2021-08-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetropolisParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist', models.CharField(choices=[('norm', 'Normal Distribution'), ('unif', 'Uniform Distribution')], help_text='Enter desired distribution', max_length=4)),
                ('lowerBound', models.DecimalField(decimal_places=3, max_digits=6)),
                ('upperBound', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
    ]
