# Generated by Django 2.2.5 on 2021-08-19 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MetropolisParameters',
            new_name='MetropolisPlot',
        ),
    ]
