# Generated by Django 2.2.5 on 2021-09-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_auto_20210819_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='metropolisplot',
            name='bins',
            field=models.IntegerField(default=41, help_text='Enter desired number of points in distribution'),
        ),
        migrations.AlterField(
            model_name='metropolisplot',
            name='lowerBound',
            field=models.DecimalField(decimal_places=3, help_text='Enter a lower bound', max_digits=6),
        ),
        migrations.AlterField(
            model_name='metropolisplot',
            name='upperBound',
            field=models.DecimalField(decimal_places=3, help_text='Enter an upper bound', max_digits=6),
        ),
    ]
