# Generated by Django 2.2.5 on 2021-09-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_auto_20210901_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metropolisplot',
            name='bins',
        ),
        migrations.AddField(
            model_name='metropolisplot',
            name='tot_samples',
            field=models.IntegerField(default=1000, help_text='Enter the desired number of drawn samples'),
        ),
    ]
