# Generated by Django 2.2.5 on 2021-09-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0005_auto_20210903_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='metropolisplot',
            name='bins',
            field=models.IntegerField(default=21, help_text='Enter desired number of points in distribution'),
        ),
    ]
