# Generated by Django 2.2.5 on 2021-09-03 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0006_metropolisplot_bins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metropolisplot',
            old_name='tot_samples',
            new_name='totSamples',
        ),
    ]
