# Generated by Django 2.2.5 on 2021-09-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0007_auto_20210903_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metropolisplot',
            name='bins',
            field=models.IntegerField(help_text='Enter desired number of points in distribution'),
        ),
        migrations.AlterField(
            model_name='metropolisplot',
            name='totSamples',
            field=models.IntegerField(help_text='Enter the desired number of drawn samples'),
        ),
    ]
